ALTER TABLE ONLY public.tagi DROP CONSTRAINT tagi_pkey;
ALTER TABLE ONLY public.paikka DROP CONSTRAINT paikka_pkey;
ALTER TABLE ONLY public.kuvaus DROP CONSTRAINT kuvaus_pkey;
ALTER TABLE ONLY public.kayttaja DROP CONSTRAINT kayttaja_pkey;
ALTER TABLE public.tagi ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.paikka ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.kuvaus ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.kayttaja ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.tagi_id_seq;
DROP TABLE public.tagi;
DROP TABLE public.paikkatagi;
DROP SEQUENCE public.paikka_id_seq;
DROP TABLE public.paikka;
DROP SEQUENCE public.kuvaus_id_seq;
DROP TABLE public.kuvaus;
DROP SEQUENCE public.kayttaja_id_seq;
DROP TABLE public.kayttaja;
DROP TYPE public.rooli;
DROP SCHEMA public;
